# Generated by Django 2.1.3 on 2018-12-21 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(help_text='Descripción de la categoría', max_length=100)),
                ('cruda', models.IntegerField()),
                ('tratada', models.IntegerField()),
                ('hr_servidas', models.IntegerField()),
                ('hr_sin_servicio', models.IntegerField()),
                ('ag_cruda_recibida', models.IntegerField()),
                ('ag_tratada_despachada', models.IntegerField()),
                ('consumo_sulfato', models.IntegerField()),
                ('consumo_cloro', models.IntegerField()),
                ('creadopor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='OperacionDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Funcionario', max_length=50)),
                ('hora', models.CharField(help_text='hora', max_length=50)),
                ('caudal_entrada_LxS', models.IntegerField()),
                ('caudal_entrada_m3', models.DecimalField(decimal_places=2, max_digits=11)),
                ('caudal_salida_LxS', models.IntegerField()),
                ('caudal_salida_m3', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sul_dial', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sul_g_minut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sul_mg_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precloracion_Lxdia', models.IntegerField()),
                ('cloracion_Lxdia', models.IntegerField()),
                ('cloracion_mg_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tq_almacenam_altura_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tq_almacenam_altura_m3', models.DecimalField(decimal_places=2, max_digits=11)),
                ('volumen_salida_acum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volumen_salida_real', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'OperacionDiaria',
            },
        ),
        migrations.CreateModel(
            name='ProcesosPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción de la categoría', max_length=100)),
                ('hora', models.IntegerField()),
                ('temperatura_ag_cruda', models.IntegerField()),
                ('ph_ag_cruda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_ag_cruda', models.IntegerField()),
                ('turbiedad_ag_cruda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_sal_sedimentadores', models.IntegerField()),
                ('turbiedad_sal_sedimentadores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cloro_res_sal_sedimentadores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph_sal_tq_desinfeccion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('turbiedad_sal_tq_desinfeccion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_sal_tq_distribucion', models.IntegerField()),
                ('ph_sal_tq_distribucion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_sal_tq_distribucion', models.IntegerField()),
                ('turbiedad_sal_tq_distribucion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alcalinidad_sal_tq_distribucion', models.IntegerField()),
                ('cloro_res_sal_tq_distribucion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'ProcesosPlantas',
            },
        ),
    ]
