# Generated by Django 2.1.3 on 2018-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20181203_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='ag_cruda_recibida',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ag_tratada_despachada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='consumo_cloro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='consumo_sulfato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cruda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='hr_servidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='hr_sin_servicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tratada',
            field=models.IntegerField(default=0),
        ),
    ]
