# Generated by Django 2.1.3 on 2018-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_auto_20181203_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesosPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción de la categoría', max_length=100)),
                ('hora', models.IntegerField()),
                ('temperatura_ag_cruda', models.IntegerField()),
                ('ph_ag_cruda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color_ag_cruda', models.IntegerField()),
                ('turbiedad_ag_cruda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color_sal_sedimentadores', models.IntegerField()),
                ('turbiedad_sal_sedimentadores', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cloro_res_sal_sedimentadores', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph_sal_tq_desinfeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('turbiedad_sal_tq_desinfeccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_sal_tq_distribucion', models.IntegerField()),
                ('ph_sal_tq_distribucion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color_sal_tq_distribucion', models.IntegerField()),
                ('turbiedad_sal_tq_distribucion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alcalinidad_sal_tq_distribucion', models.IntegerField()),
                ('cloro_res_sal_tq_distribucion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProcesosPlantas',
            },
        ),
    ]
