# Generated by Django 2.1.3 on 2018-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_remove_categoria_creadopor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesosplanta',
            name='cloro_res_sal_sedimentadores',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='cloro_res_sal_tq_distribucion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='ph_ag_cruda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='ph_sal_tq_distribucion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='turbiedad_ag_cruda',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='turbiedad_sal_sedimentadores',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='turbiedad_sal_tq_desinfeccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='turbiedad_sal_tq_distribucion',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
