# Generated by Django 2.1.3 on 2018-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_auto_20181210_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesosplanta',
            name='alcalinidad_sal_tq_distribucion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='color_sal_sedimentadores',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='color_sal_tq_distribucion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='hora',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='temperatura_ag_cruda',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='procesosplanta',
            name='temperatura_sal_tq_distribucion',
            field=models.IntegerField(blank=True),
        ),
    ]
